export interface MedicalCollege {
  id: number;
  name: string;
  state: string;
}

export const medicalColleges: MedicalCollege[] = [
  { id: 1, name: "Andaman & Nicobar Islands Institute of Medical Sciences, Port Blair", state: "Andaman Nicobar Islands" },
  { id: 2, name: "All India Institute of Medical Sciences, Mangalagiri, Vijayawada", state: "Andhra Pradesh" },
  { id: 3, name: "ACSR Government Medical College", state: "Andhra Pradesh" },
  { id: 4, name: "Alluri Sitaram Raju Academy of Medical Sciences, Eluru", state: "Andhra Pradesh" },
  { id: 5, name: "Andhra Medical College, Visakhapatnam", state: "Andhra Pradesh" },
  { id: 6, name: "Anna Gowri Medical College and Hospital", state: "Andhra Pradesh" },
  { id: 7, name: "Apollo Institute of Medical Sciences and Research, Chittoor", state: "Andhra Pradesh" },
  { id: 8, name: "Dr. P.S.I. Medical College , Chinoutpalli", state: "Andhra Pradesh" },
  { id: 9, name: "Fathima Instt. of Medical Sciences, Kadapa", state: "Andhra Pradesh" },
  { id: 10, name: "Gayathri Vidya Parishad Institute of Health Care & Medical Technology, Visakhapatnam", state: "Andhra Pradesh" },
  { id: 11, name: "GITAM Institute of Medical Sciences and Research, Visakhapatnam", state: "Andhra Pradesh" },
  { id: 12, name: "Government Medical College, Ananthapuram", state: "Andhra Pradesh" },
  { id: 13, name: "Government Medical College, Eluru", state: "Andhra Pradesh" },
  { id: 14, name: "Government Medical College, Machilipatnam", state: "Andhra Pradesh" },
  { id: 15, name: "Government Medical College, Nandyal", state: "Andhra Pradesh" },
  { id: 16, name: "Government Medical College, Paderu", state: "Andhra Pradesh" },
  { id: 17, name: "Government Medical College, Rajamahendravaram", state: "Andhra Pradesh" },
  { id: 18, name: "Government medical college, vizianagaram", state: "Andhra Pradesh" },
  { id: 19, name: "Government Siddhartha Medical College, Vijaywada", state: "Andhra Pradesh" },
  { id: 20, name: "Great Eastern Medical School and Hospital, Srikakulam", state: "Andhra Pradesh" },
  { id: 21, name: "GSL Medical College, Rajahmundry", state: "Andhra Pradesh" },
  { id: 22, name: "Guntur Medical College, Guntur", state: "Andhra Pradesh" },
  { id: 23, name: "Katuri Medical College, Guntur", state: "Andhra Pradesh" },
  { id: 24, name: "Konaseema Institute of Medical Sciences & Research Foundation, Amalapuram", state: "Andhra Pradesh" },
  { id: 25, name: "Kurnool Medical College, Kurnool", state: "Andhra Pradesh" },
  { id: 26, name: "Maharajah Institute of Medical Sciences, Vizianagaram", state: "Andhra Pradesh" },
  { id: 27, name: "Narayana Medical College, Nellore", state: "Andhra Pradesh" },
  { id: 28, name: "Nimra Institute of Medical Sciences, Krishna Dist.", state: "Andhra Pradesh" },
  { id: 29, name: "NRI Institute of Medical Sciences, Visakhapatnam", state: "Andhra Pradesh" },
  { id: 30, name: "NRI Medical College, Guntur", state: "Andhra Pradesh" },
  { id: 31, name: "P E S Institute Of Medical Sciences and Research, Kuppam", state: "Andhra Pradesh" },
  { id: 32, name: "Government Medical College, Kadapa ( previously Rajiv Gandhi Institute of Medical Sciences, Kadapa)", state: "Andhra Pradesh" },
  { id: 33, name: "Government Medical College, Ongole (previously Rajiv Gandhi Institute of Medical Sciences, Ongole)", state: "Andhra Pradesh" },
  { id: 34, name: "Rajiv Gandhi Institute of Medical Sciences, Srikakulam", state: "Andhra Pradesh" },
  { id: 35, name: "Rangaraya Medical College, Kakinada", state: "Andhra Pradesh" },
  { id: 36, name: "S V Medical College, Tirupati", state: "Andhra Pradesh" },
  { id: 37, name: "Santhiram Medical College, Nandyal", state: "Andhra Pradesh" },
  { id: 38, name: "Sri Balaji Medical College, Hospital and Research Instiutute, Chittoor", state: "Andhra Pradesh" },
  { id: 39, name: "SVIMS - Sri Padmavathi Medical College for Women, Alipiri Road, Tirupati", state: "Andhra Pradesh" },
  { id: 40, name: "Viswabharathi Medical College", state: "Andhra Pradesh" },
  { id: 41, name: "Tomo Riba Institute of Health & Medical Sciences, Naharlagun", state: "Arunachal Pradesh" },
  { id: 42, name: "All India Institute of Medical Sciences, Guwahati", state: "Assam" },
  { id: 43, name: "Assam Medial College, Dibrugarh", state: "Assam" },
  { id: 44, name: "Dhubri Medical College, Dhubri", state: "Assam" },
  { id: 45, name: "Diphu Medical College & Hospital, Diphu, Assam", state: "Assam" },
  { id: 46, name: "ESIC Medical College and Hospital, Beltola", state: "Assam" },
  { id: 47, name: "Barpeta Medical College & Hospital, Barpeta, Assam", state: "Assam" },
  { id: 48, name: "Gauhati Medical College, Guwahati", state: "Assam" },
  { id: 49, name: "Jorhat Medical College & Hospital , Jorhat", state: "Assam" },
  { id: 50, name: "Kokrajhar Medical College", state: "Assam" },
  { id: 51, name: "Lakhimpur Medical College", state: "Assam" },
  { id: 52, name: "Nagaon Medical College", state: "Assam" },
  { id: 53, name: "Nalbari Medical College, Nalbari", state: "Assam" },
  { id: 54, name: "Pragjyotishpur Medical College", state: "Assam" },
  { id: 55, name: "Silchar Medical College, Silchar", state: "Assam" },
  { id: 56, name: "Tezpur Medical College & Hospital, Tezpur", state: "Assam" },
  { id: 57, name: "Tinsukia Medical College - Assam Pin - 786146", state: "Assam" },
  { id: 58, name: "All India Institute of Medical Sciences, Patna", state: "Bihar" },
  { id: 59, name: "Anugrah Narayan Magadh Medical College, Gaya", state: "Bihar" },
  { id: 60, name: "Darbhanga Medical College, Lehriasarai", state: "Bihar" },
  { id: 61, name: "Employees State Insurance Corporation Medical College, Patna", state: "Bihar" },
  { id: 62, name: "Government Medical College, Bettiah", state: "Bihar" },
  { id: 63, name: "Government Medical College, Purnea", state: "Bihar" },
  { id: 64, name: "Himalaya Medical College and Hospital , Patna, Bihar", state: "Bihar" },
  { id: 65, name: "Indira Gandhi Institute of Medical Sciences, Sheikhpura, Patna", state: "Bihar" },
  { id: 66, name: "Jannayak Karpoori Thakur Medical College & Hospital, Madhepura, Bihar", state: "Bihar" },
  { id: 67, name: "Jawaharlal Nehru Medical College, Bhagalpur", state: "Bihar" },
  { id: 68, name: "Katihar Medical College, Katihar", state: "Bihar" },
  { id: 69, name: "Lord Buddha Koshi Medical College and Hospital, Saharsa", state: "Bihar" },
  { id: 70, name: "Madhubani Medical College, Madhubani", state: "Bihar" },
  { id: 71, name: "MAHABODHI MEDICAL COLLEGE & HOSPITAL", state: "Bihar" },
  { id: 72, name: "Mata Gujri Memorial Medical College, Kishanganj", state: "Bihar" },
  { id: 73, name: "Nalanda Medical College, Patna", state: "Bihar" },
  { id: 74, name: "Narayan Medical College & Hospital, Sasaram", state: "Bihar" },
  { id: 75, name: "Netaji Subhas Medical College & Hospital, Amhara, Bihta, Patna", state: "Bihar" },
  { id: 76, name: "Patna Medical College, Patna", state: "Bihar" },
  { id: 77, name: "Radha Devi Jageshwari Memorial Medical College and Hospital", state: "Bihar" },
  { id: 78, name: "Shree Narayan Medical Institute and Hospital", state: "Bihar" },
  { id: 79, name: "Shri Krishna Medical College, Muzzafarpur", state: "Bihar" },
  { id: 80, name: "SHYAMLAL CHANDRASHEKHAR MEDICAL COLLEGE & S P N M HOPSITAL", state: "Bihar" },
  { id: 81, name: "Bhagwan Mahavir Institute of Medical Sciences, Pawapuri (formerly Vardhman Institute of Medical Sciences, Pawapuri, Nalanda)", state: "Bihar" },
  { id: 82, name: "VIRAAT RAMAYAN INSTITUTE OF MEDICAL SCIENCES", state: "Bihar" },
  { id: 83, name: "Government Medical College, Chandigarh", state: "Chandigarh" },
  { id: 84, name: "All India Institute of Medical Sciences, Raipur", state: "Chattisgarh" },
  { id: 85, name: "Abhishek Mishra Memorial Medical College & RC Bhiali Distt. Durg CG", state: "Chattisgarh" },
  { id: 86, name: "Chandulal Chandrakar Memorial Medical College, Durg", state: "Chattisgarh" },
  { id: 87, name: "Chhattisgarh Institute of Medical Sciences, Bilaspur", state: "Chattisgarh" },
  { id: 88, name: "Government Medical College (Bharat Ratna Shri Atal Bihari Vajpyee Memorial Med. Col.), Rajnandgaon", state: "Chattisgarh" },
  { id: 89, name: "Rajmata Shrimata Devendra Kumari Singhdeo Government Medical College, Ambikapur (Surguja), Chhattisgarh", state: "Chattisgarh" },
  { id: 90, name: "Government Medical College, Korba", state: "Chattisgarh" },
  { id: 91, name: "Government Medical College, Mahasamund", state: "Chattisgarh" },
  { id: 92, name: "Late Shri Baliram Kashyap Memorial NDMC Govt. Medical College, Jagdalpur", state: "Chattisgarh" },
  { id: 93, name: "Late Shri Lakhi Ram Agrawal Memorial Govt. Medical College, Raigarh", state: "Chattisgarh" },
  { id: 94, name: "Pt. J N M Medical College, Raipur", state: "Chattisgarh" },
  { id: 95, name: "Raipur Institute of Medical Sciences (RIMS), Raipur", state: "Chattisgarh" },
  { id: 96, name: "Shri Balaji Institute of Medical Science", state: "Chattisgarh" },
  { id: 97, name: "Shri Rawatpura Sarkar Institute of Medical Sciences and Research Atal Nagar, Dist- Raipur (C.G.)", state: "Chattisgarh" },
  { id: 98, name: "Shri Shankaracharya Institute of Medical Sciences, Bhilai", state: "Chattisgarh" },
  { id: 99, name: "Shrimati Indira Gandhi Memorial Govt. Medical College, Kanker, Chattisgarh (previously Government Medical College, Kanker)", state: "Chattisgarh" },
  { id: 100, name: "NAMO Medical Education and Research Institute, Silvassa (Formerly known as Shri Vinoba Bhave Institute of Medical Sciences, (Govt. Medical College) Silvassa, U.T)", state: "Dadra and Nagar Haveli" },
  { id: 101, name: "All India Institute of Medical Sciences, New Delhi", state: "Delhi" },
  { id: 102, name: "Army College of Medical Sciences, New Delhi", state: "Delhi" },
  { id: 103, name: "Dr. Baba Saheb Ambedkar Medical College, Rohini, Delhi", state: "Delhi" },
  { id: 104, name: "ESIC Medical College & Hospital, Basaidarapur, New Delhi", state: "Delhi" },
  { id: 105, name: "Hamdard Institute of Medical Sciences & Research, New Delhi", state: "Delhi" },
  { id: 106, name: "Maulana Azad Medical College, New Delhi", state: "Delhi" },
  { id: 107, name: "North Delhi Muncipal Corporation Medical College, Delhi", state: "Delhi" },
  { id: 108, name: "Atal Bihari Vajpayee Institute of Medical Sciences and Dr. RML Hospital, New Delhi", state: "Delhi" },
  { id: 109, name: "Lady Hardinge Medical College, New Delhi", state: "Delhi" },
  { id: 110, name: "Vardhman Mahavir Medical College & Safdarjung Hospital, Delhi", state: "Delhi" },
  { id: 111, name: "University College of Medical Sciences & GTB Hospital, New Delhi", state: "Delhi" },
  { id: 112, name: "Goa Medical College, Panaji", state: "Goa" },
  { id: 113, name: "All India Institute of Medical Sciences, Rajkot", state: "Gujarat" },
  { id: 114, name: "Narendra Modi Medical College, Ahmedabad ( previously Ahmedabad Municipal Coporation Medical Education Trust Medical College, Ahmedabad)", state: "Gujarat" },
  { id: 115, name: "Ananya College of Medicine & Research, Kalol", state: "Gujarat" },
  { id: 116, name: "B J Medical College, Ahmedabad", state: "Gujarat" },
  { id: 117, name: "Banas Medical College and Research Institute, Palanpur, Gujarat", state: "Gujarat" },
  { id: 118, name: "Bhagyoday Medical College", state: "Gujarat" },
  { id: 119, name: "CU Shah Medical College, Surendra Nagar", state: "Gujarat" },
  { id: 120, name: "Dr. Kiran C.Patel Medical College and Research Institute", state: "Gujarat" },
  { id: 121, name: "Dr. M.K. Shah Medical College & Research Centre, Ahmedabad", state: "Gujarat" },
  { id: 122, name: "Dr. N.D. Desai Faculty of Medical Science and Research, Nadiad", state: "Gujarat" },
  { id: 123, name: "ESIC MEDICAL COLLEGE NARODA BAPUNAGAR, AHMEDABAD", state: "Gujarat" },
  { id: 124, name: "GCS Medical College, Ahmedabad", state: "Gujarat" },
  { id: 125, name: "GMERS Medical College, Dharpur Patan", state: "Gujarat" },
  { id: 126, name: "GMERS Medical College, Gandhinagar", state: "Gujarat" },
  { id: 127, name: "GMERS Medical College, Gotri, Vadodara", state: "Gujarat" },
  { id: 128, name: "GMERS Medical College, Hadiyol, Himmatnagar", state: "Gujarat" },
  { id: 129, name: "GMERS Medical College, Junagadh", state: "Gujarat" },
  { id: 130, name: "GMERS Medical College, Rajpipla", state: "Gujarat" },
  { id: 131, name: "GMERS Medical College, Sola, Ahmedabad", state: "Gujarat" },
  { id: 132, name: "GMERS Medical College, Vadnagar, Mehsana", state: "Gujarat" },
  { id: 133, name: "GMERS Medical College, Valsad", state: "Gujarat" },
  { id: 134, name: "Government Medical College, Bhavnagar", state: "Gujarat" },
  { id: 135, name: "Government Medical College, Morbi", state: "Gujarat" },
  { id: 136, name: "GMERS Medical College, Navsari", state: "Gujarat" },
  { id: 137, name: "Government Medical College, Panchmahal Godhra", state: "Gujarat" },
  { id: 138, name: "Government Medical College, Porbandar", state: "Gujarat" },
  { id: 139, name: "Government Medical College, Surat", state: "Gujarat" },
  { id: 140, name: "Gujarat Adani Institute of Medical Sciences, Bhuj", state: "Gujarat" },
  { id: 141, name: "Kiran Medical College", state: "Gujarat" },
  { id: 142, name: "Matushri prabhaben khodabhai boghara medical college & research centre", state: "Gujarat" },
  { id: 143, name: "Medical College, Baroda", state: "Gujarat" },
  { id: 144, name: "MP Shah Medical College, Jamnagar", state: "Gujarat" },
  { id: 145, name: "Nootan Medical College and Research Centre, Mehsana", state: "Gujarat" },
  { id: 146, name: "Pandit Deendayal Upadhyay Medical College, Rajkot", state: "Gujarat" },
  { id: 147, name: "Parul Institute of Medical Sciences & Research, Vadodara", state: "Gujarat" },
  { id: 148, name: "Pramukhswami Medical College, Karmsad", state: "Gujarat" },
  { id: 149, name: "SAL Institute of Medical Sciences, Ahmedabad", state: "Gujarat" },
  { id: 150, name: "SBKS Medical Instt. & Research Centre, Vadodra", state: "Gujarat" },
  { id: 151, name: "Shantabaa Medical College, Amreli", state: "Gujarat" },
  { id: 152, name: "Smt. N.H.L.Municipal Medical College, Ahmedabad", state: "Gujarat" },
  { id: 153, name: "Surat Municipal Institute of Medical Education & Research, Surat", state: "Gujarat" },
  { id: 154, name: "SWAMIINARAYAN INSTITUTE OF MEDICAL SCIENCES & RESEARCH", state: "Gujarat" },
  { id: 155, name: "Zydus Medical College & Hospital, Dahod", state: "Gujarat" },
  { id: 156, name: "Adesh Medical College and Hospital, Shahabad, Kurukshetra, Haryana", state: "Haryana" },
  { id: 157, name: "Al Falah School of Medical Sciences & Research Centre, Faridabad", state: "Haryana" },
  { id: 158, name: "Amrita School of Medicine", state: "Haryana" },
  { id: 159, name: "BPS Government Medical College for Women, Sonepat", state: "Haryana" },
  { id: 160, name: "Employees State Insurance Corporation Medical College, Faridabad", state: "Haryana" },
  { id: 161, name: "Faculty of Medicine and Health Sciences, Gurgaon (Formarly SGGST Medical College & R Centre,Gurgaon)", state: "Haryana" },
  { id: 162, name: "Kalpana Chawala Govt. Medical College, Karnal, Haryana", state: "Haryana" },
  { id: 163, name: "Maharaja Agrasen Medical College, Agroha", state: "Haryana" },
  { id: 164, name: "Maharishi Chyawan Medical College, Koriawas", state: "Haryana" },
  { id: 165, name: "Maharishi Markandeshwar College of Medical Sciences & Research, Sadopur", state: "Haryana" },
  { id: 166, name: "Maharishi Markandeshwar Institute Of Medical Sciences & Research, Mullana, Ambala", state: "Haryana" },
  { id: 167, name: "N.C. Medical College & Hospital, Panipat", state: "Haryana" },
  { id: 168, name: "PT NEKI RAM SHARMA GOVERNMENT MEDICAL COLLEGE, BHIWANI", state: "Haryana" },
  { id: 169, name: "Pt. B D Sharma Postgraduate Institute of Medical Sciences, Rohtak (Haryana)", state: "Haryana" },
  { id: 170, name: "Shaheed Hasan Khan Mewati Government Medical College, Nalhar", state: "Haryana" },
  { id: 171, name: "Shri Atal Bihari Vajpayee Government Medical College, Faridabad", state: "Haryana" },
  { id: 172, name: "World College of Medical Sciences & Researc, Jhajjar, Haryana", state: "Haryana" },
  { id: 173, name: "All India Institute of Medical Sciences, Bilaspur", state: "Himachal Pradesh" },
  { id: 174, name: "Dr. Radhakrishnan Government Medical College, Hamirpur, H.P", state: "Himachal Pradesh" },
  { id: 175, name: "Dr. Rajendar Prasad Government Medical College, Tanda, H.P", state: "Himachal Pradesh" },
  { id: 176, name: "Government Medical College, Nahan, Sirmour H.P.", state: "Himachal Pradesh" },
  { id: 177, name: "Indira Gandhi Medical College, Shimla", state: "Himachal Pradesh" },
  { id: 178, name: "Maharishi Markandeshwar Medical College & Hospital, Solan", state: "Himachal Pradesh" },
  { id: 179, name: "Pt. Jawahar Lal Nehru Government Medical College, Chamba", state: "Himachal Pradesh" },
  { id: 180, name: "Shri Lal Bahadur Shastri Government Medical College, Mandi, HP", state: "Himachal Pradesh" },
  { id: 181, name: "All India Institute of Medical Sciences, Vijaypur", state: "Jammu & Kashmir" },
  { id: 182, name: "Acharya Shri Chander College of Medical Sciences, Jammu", state: "Jammu & Kashmir" },
  { id: 183, name: "Government Medical College Handwara", state: "Jammu & Kashmir" },
  { id: 184, name: "Government Medical College Udhampur", state: "Jammu & Kashmir" },
  { id: 185, name: "Government Medical College, Anantnag", state: "Jammu & Kashmir" },
  { id: 186, name: "Government Medical College, Baramulla", state: "Jammu & Kashmir" },
  { id: 187, name: "Government Medical College, Jammu", state: "Jammu & Kashmir" },
  { id: 188, name: "Government Medical College, Kathua", state: "Jammu & Kashmir" },
  { id: 189, name: "Government Medical College, Rajouri, J&K", state: "Jammu & Kashmir" },
  { id: 190, name: "Government Medical College, Srinagar", state: "Jammu & Kashmir" },
  { id: 191, name: "Govt. Medical College, Doda, Kashmir", state: "Jammu & Kashmir" },
  { id: 192, name: "Sher-I-Kashmir Instt. Of Medical Sciences, Srinagar", state: "Jammu & Kashmir" },
  { id: 193, name: "SHRI MATA VAISHNO DEVI INSTITUTE OF MEDICAL EXCELLENCE", state: "Jammu & Kashmir" },
  { id: 194, name: "All India Institute of Medical Sciences, Deoghar", state: "Jharkhand" },
  { id: 195, name: "Dumka Medical College, Dighi Dumka", state: "Jharkhand" },
  { id: 196, name: "Hazaribagh Medical College, Hazaribagh", state: "Jharkhand" },
  { id: 197, name: "Laxmi Chandravansi Medical College & Hospital", state: "Jharkhand" },
  { id: 198, name: "M G M Medical College, Jamshedpur", state: "Jharkhand" },
  { id: 199, name: "Manipal Tata Medical College,Baridih Jameshedpur", state: "Jharkhand" },
  { id: 200, name: "NETAJI SUBHAS MEDICAL COLLEGE AND HOSPITAL", state: "Jharkhand" },
  { id: 201, name: "Palamu Medical College, Palamu", state: "Jharkhand" },
  { id: 202, name: "Rajendra Institute of Medical Sciences, Ranchi", state: "Jharkhand" },
  { id: 203, name: "Shaheed Nirmal Mahto Medical College & Hospital, Dhanbad (formely known as Patliputra Medical College, Dhanbad)", state: "Jharkhand" },
  { id: 204, name: "G R Medical College Hospital & Research Centre", state: "Karnataka" },
  { id: 205, name: "A J Institute of Medical Sciences & Research Centre, Mangalore", state: "Karnataka" },
  { id: 206, name: "Adichunchanagiri Institute of Medical Sciences, Bellur", state: "Karnataka" },
  { id: 207, name: "Akash Institute of Medical Sciences & Research Centre, Devanhalli, Bangalore, Karnataka", state: "Karnataka" },
  { id: 208, name: "Al-Ameen Medical College, Bijapur", state: "Karnataka" },
  { id: 209, name: "Bangalore Medical College and Research Institute, Bangalore", state: "Karnataka" },
  { id: 210, name: "Basaveswara Medical College and Hospital, Chitradurga", state: "Karnataka" },
  { id: 211, name: "Belagavi Institute of Medical Sciences, Belagavi", state: "Karnataka" },
  { id: 212, name: "BGS Global Institute of Medical Sciences, Bangalore", state: "Karnataka" },
  { id: 213, name: "BGS Medical College and Hospital Bengaluru, Karnataka", state: "Karnataka" },
  { id: 214, name: "Bidar Institute of Medical Sciences, Bidar", state: "Karnataka" },
  { id: 215, name: "Chamrajanagar Institute of Medical Sciences, Karnataka", state: "Karnataka" },
  { id: 216, name: "Nandi Medical College and Research Institute Chikkaballapura (Chikkaballapura Institute of Medical Sciences Chikkaballapura )", state: "Karnataka" },
  { id: 217, name: "Chikkamagaluru Institute of Medical Sciences, Chikkamagaluru", state: "Karnataka" },
  { id: 218, name: "Chitradurga Medical College and Research Institute", state: "Karnataka" },
  { id: 219, name: "Dr BR Ambedkar Medical College, Bangalore", state: "Karnataka" },
  { id: 220, name: "Dr. Chandramma Dayananda Sagar Instt. of Medical Education & Research, Harohalli, Hubli", state: "Karnataka" },
  { id: 221, name: "East Point College of Medical Sciences & Research Centre, Bangalore", state: "Karnataka" },
  { id: 222, name: "Employees State Insurance Corporation Medical College, Bangalore", state: "Karnataka" },
  { id: 223, name: "Employees State Insurance Corporation Medical College, Gulbarga", state: "Karnataka" },
  { id: 224, name: "FAROOKH ACADEMY OF MEDICAL EDUCATION HOSPITAL AND RESEARCH INSTITUTE", state: "Karnataka" },
  { id: 225, name: "Father Mullers Medical College, Mangalore", state: "Karnataka" },
  { id: 226, name: "Gulbarga Institute of Medical Sciences, Gulbarga", state: "Karnataka" },
  { id: 227, name: "Hassan Institute of Medical Sciences, Hassan", state: "Karnataka" },
  { id: 228, name: "Haveri Institute of Medical Sciences, Haveri", state: "Karnataka" },
  { id: 229, name: "Jagadguru Gangadhar Mahaswamigalu Moorusavirmath Medical College JGMMMC", state: "Karnataka" },
  { id: 230, name: "Jawaharlal Nehru Medical College, Belgaum", state: "Karnataka" },
  { id: 231, name: "JJM Medical College, Davangere", state: "Karnataka" },
  { id: 232, name: "JSS Medical College, Mysore", state: "Karnataka" },
  { id: 233, name: "K S Hegde Medical Academy, Mangalore", state: "Karnataka" },
  { id: 234, name: "K V G Medical College, Sullia", state: "Karnataka" },
  { id: 235, name: "K.H. Patil Institute of Medical Sciences (previously Gadag Institute of Medical Sciences, Mallasamudra, Mulgund Road, Gadag)", state: "Karnataka" },
  { id: 236, name: "Kanachur Institute of Medical Sciences, Mangalore", state: "Karnataka" },
  { id: 237, name: "Karnataka Medical College and Research Institute, Hubballi, Karnataka", state: "Karnataka" },
  { id: 238, name: "Karwar Institute of Medical Sciences, Karwar", state: "Karnataka" },
  { id: 239, name: "Kasturba Medical College, Mangalore", state: "Karnataka" },
  { id: 240, name: "Kasturba Medical College, Manipal", state: "Karnataka" },
  { id: 241, name: "Kempegowda Institute of Medical Sciences, Bangalore", state: "Karnataka" },
  { id: 242, name: "Khaja Bandanawaz University - Faculty of Medical Sciences, Gulbarga", state: "Karnataka" },
  { id: 243, name: "Kodagu Institute of Medical Sciences, Kodagu", state: "Karnataka" },
  { id: 244, name: "Koppal Institute of Medical Sciences, Koppal", state: "Karnataka" },
  { id: 245, name: "M S Ramaiah Medical College, Bangalore", state: "Karnataka" },
  { id: 246, name: "Mahadevappa Rampure Medical College, Kalaburagi, Gulbarga", state: "Karnataka" },
  { id: 247, name: "Mandya Institute of Medical Sciences, Mandya", state: "Karnataka" },
  { id: 248, name: "MVJ Medical College and Research Hospital, Bangalore", state: "Karnataka" },
  { id: 249, name: "Mysore Medical College and Research Instt. (Prev.name Government Medical College), Mysore", state: "Karnataka" },
  { id: 250, name: "Navodaya Medical College, Raichur", state: "Karnataka" },
  { id: 251, name: "PES University Institute of Medical Sciences and Reseach Bangalore", state: "Karnataka" },
  { id: 252, name: "Raichur Institute of Medical Sciences, Raichur", state: "Karnataka" },
  { id: 253, name: "Raja Rajeswari Medical College & Hospital, Bangalore", state: "Karnataka" },
  { id: 254, name: "S S Institute of Medical Sciences& Research Centre, Davangere", state: "Karnataka" },
  { id: 255, name: "S. Nijalingappa Medical College & HSK Hospital & Research Centre, Bagalkot", state: "Karnataka" },
  { id: 256, name: "Sapthagiri Institute of Medical Sciences & Research Centre, Bangalore", state: "Karnataka" },
  { id: 257, name: "SDM College of Medical Sciences & Hospital, Sattur, Dharwad", state: "Karnataka" },
  { id: 258, name: "Shimoga Institute of Medical Sciences, Shimoga", state: "Karnataka" },
  { id: 259, name: "Shri Atal Bihari Vajpayee Medical College & Research Institute", state: "Karnataka" },
  { id: 260, name: "Shri B M Patil Medical College, Hospital & Research Centre, Vijayapura (Bijapur", state: "Karnataka" },
  { id: 261, name: "Shridevi Institute of Medical Sciences & Research Hospital, Tumkur", state: "Karnataka" },
  { id: 262, name: "Siddaganga Medical College and Research Institute, Tumakuru", state: "Karnataka" },
  { id: 263, name: "SR Patil Medical College and Hospital Distt Bagalkot", state: "Karnataka" },
  { id: 264, name: "Sri Chamundeshwari Medical College Hospital & Research Institute", state: "Karnataka" },
  { id: 265, name: "Sri Devaraj URS Medical College, Kolar", state: "Karnataka" },
  { id: 266, name: "Sri Madhusudan Sai Institute of Medical Sciences & Research, Chikballapur", state: "Karnataka" },
  { id: 267, name: "Sri siddhartha Institute of Medical Sciences & Research Centre, Bangalore", state: "Karnataka" },
  { id: 268, name: "Sri Siddhartha Medical College, Tumkur", state: "Karnataka" },
  { id: 269, name: "Srinivas Institute of Medical Research Centre, Srinivasnagar, Mangalore", state: "Karnataka" },
  { id: 270, name: "St. Johns Medical College, Bangalore", state: "Karnataka" },
  { id: 271, name: "Subbaiah Institute of Medical Sciences, Shimoga, Karnataka", state: "Karnataka" },
  { id: 272, name: "The Oxford Medical College, Hospital & Research Centre, Bangalore", state: "Karnataka" },
  { id: 273, name: "Vijaynagar Institute of Medical Sciences, Bellary", state: "Karnataka" },
  { id: 274, name: "Vydehi Institute Of Medical Sciences & Research Centre, Bangalore", state: "Karnataka" },
  { id: 275, name: "Yadgiri Institute of Medical Sciences, Yadgiri", state: "Karnataka" },
  { id: 276, name: "Yenepoya Medical College, Mangalore", state: "Karnataka" },
  { id: 277, name: "Sambharam Institute of Medical Sciences & Research, Kolar", state: "Karnataka" },
  { id: 278, name: "Kannur Medical College, Kannur", state: "Kerala" },
  { id: 279, name: "Al-Azhar Medical College and Super Speciality Hospital, Thodupuzha", state: "Kerala" },
  { id: 280, name: "Amala Institute of Medical Sciences, Thrissur", state: "Kerala" },
  { id: 281, name: "Amrita School of Medicine, Elamkara, Kochi", state: "Kerala" },
  { id: 282, name: "Azeezia Institute of Medical Sciences and Research", state: "Kerala" },
  { id: 283, name: "Believers Church Medical College Hospital, Thiruvalla, Kerala", state: "Kerala" },
  { id: 284, name: "Dr. Moopen Medical College Wayanad, Kerala", state: "Kerala" },
  { id: 285, name: "Dr. Somervel Memorial CSI Hospital & Medical College, Karakonam, Thiruvananthapuram", state: "Kerala" },
  { id: 286, name: "Government Medical College (Institute of Integrated Medical Sciences), Yakkara, Palakkad", state: "Kerala" },
  { id: 287, name: "Government Medical College Kasaragod", state: "Kerala" },
  { id: 288, name: "Government Medical College, Ernakulam", state: "Kerala" },
  { id: 289, name: "Government Medical College, Idukki", state: "Kerala" },
  { id: 290, name: "Government Medical College, Konni", state: "Kerala" },
  { id: 291, name: "Government Medical College, Kottayam", state: "Kerala" },
  { id: 292, name: "Government Medical College, Kozhikode, Calicut", state: "Kerala" },
  { id: 293, name: "Government Medical College, Manjeri, Malapuram Dist.", state: "Kerala" },
  { id: 294, name: "Government Medical College, Parippally, Kollam", state: "Kerala" },
  { id: 295, name: "Government Medical College, Thrissur", state: "Kerala" },
  { id: 296, name: "Government Medical College, Wayanad", state: "Kerala" },
  { id: 297, name: "Govt. Medical College,Pariyaram, Kannur (Prev. Known as Academy of Medical Sciences)", state: "Kerala" },
  { id: 298, name: "Jubilee Mission Medical College & Research Institute, Thrissur", state: "Kerala" },
  { id: 299, name: "Karuna Medical College, Palakkad", state: "Kerala" },
  { id: 300, name: "Kerala Medical College, Mangode", state: "Kerala" },
  { id: 301, name: "KMCT Medical College, Kozhikode, Calicut", state: "Kerala" },
  { id: 302, name: "M E S Medical College , Perintalmanna Malappuram Distt.Kerala", state: "Kerala" },
  { id: 303, name: "Malabar Medical College, Kozhikode, Calicut", state: "Kerala" },
  { id: 304, name: "Malankara Orthodox Syrian Church Medical College, Kolenchery", state: "Kerala" },
  { id: 305, name: "Medical College, Thiruvananthapuram", state: "Kerala" },
  { id: 306, name: "Mount Zion Medical College, Chayalode, Ezhamkulam Adoor, Pathanamthitta", state: "Kerala" },
  { id: 307, name: "P K Das Institute of Medical Sciences, Palakkad, Kerala", state: "Kerala" },
  { id: 308, name: "Palakkad Institute of Medical Sciences, Palakkad", state: "Kerala" },
  { id: 309, name: "Pushpagiri Institute Of Medical Sciences and Research Centre, Tiruvalla", state: "Kerala" },
  { id: 310, name: "Sree Gokulam Medical College Trust & Research Foundation, Trivandrum", state: "Kerala" },
  { id: 311, name: "Sree Narayana Instt. of Medical Sciences, Chalakka, Ernakulam", state: "Kerala" },
  { id: 312, name: "Sree Uthradom Thiurnal Academy of Medical Sciences, Trivandrum", state: "Kerala" },
  { id: 313, name: "T D Medical College, Alleppey (Allappuzha)", state: "Kerala" },
  { id: 314, name: "Travancore Medical College, Kollam", state: "Kerala" },
  { id: 315, name: "All India Institute of Medical Sciences, Bhopal", state: "Madhya Pradesh" },
  { id: 316, name: "Amaltas Institute of Medical Sciences, Dewas", state: "Madhya Pradesh" },
  { id: 317, name: "Bundelkhand Medical College, Sagar", state: "Madhya Pradesh" },
  { id: 318, name: "Chirayu Medical College and Hospital, Bairagarh, Bhopal", state: "Madhya Pradesh" },
  { id: 319, name: "ESIC MEDICAL COLLEGE AND HOSPITAL,INDORE", state: "Madhya Pradesh" },
  { id: 320, name: "Gajra Raja Medical College, Gwalior", state: "Madhya Pradesh" },
  { id: 321, name: "Gandhi Medical College, Bhopal", state: "Madhya Pradesh" },
  { id: 322, name: "GOVERMENT MEDICAL COLLEGE, SHEOPUR", state: "Madhya Pradesh" },
  { id: 323, name: "GOVERNMENT MEDICAL COLLEGE SINGRAULI", state: "Madhya Pradesh" },
  { id: 324, name: "Government Medical College, Chhindwara, MP", state: "Madhya Pradesh" },
  { id: 325, name: "Government Medical College, Datia, MP", state: "Madhya Pradesh" },
  { id: 326, name: "Government Medical College, Khandwa, MP", state: "Madhya Pradesh" },
  { id: 327, name: "Dr. Laxminarayan Pandey Government Medical College, Ratlam (M.P.)", state: "Madhya Pradesh" },
  { id: 328, name: "Government Medical College, Satna", state: "Madhya Pradesh" },
  { id: 329, name: "Government Medical College, Seoni", state: "Madhya Pradesh" },
  { id: 330, name: "Government Medical College, Shahdol, MP", state: "Madhya Pradesh" },
  { id: 331, name: "Government Medical College, Shivpuri, MP", state: "Madhya Pradesh" },
  { id: 332, name: "Government Medical College, Vidisha, MP", state: "Madhya Pradesh" },
  { id: 333, name: "Index Medical College Hospital & Research Centre, Indore", state: "Madhya Pradesh" },
  { id: 334, name: "L.N. Medical College and Research Centre, Bhopal", state: "Madhya Pradesh" },
  { id: 335, name: "LNCT Medical College & Sewakunj Hospital, Indore", state: "Madhya Pradesh" },
  { id: 336, name: "M G M Medical College, Indore", state: "Madhya Pradesh" },
  { id: 337, name: "Mahaveer Institute of Medical Sciences & Research, Bhopal", state: "Madhya Pradesh" },
  { id: 338, name: "MANSAROVAR MEDICAL COLLEGE AND MGU HOSPITAL", state: "Madhya Pradesh" },
  { id: 339, name: "Netaji Subhash Chandra Bose Medical College, Jabalpur", state: "Madhya Pradesh" },
  { id: 340, name: "Peoples College of Medical Sciences & Research Centre, Bhanpur, Bhopal", state: "Madhya Pradesh" },
  { id: 341, name: "Ram Krishna College Hospital & Research Centre, Bhopal", state: "Madhya Pradesh" },
  { id: 342, name: "RKDF Medical College Hospital & Research Centre, Jatkhedi, Bhopal", state: "Madhya Pradesh" },
  { id: 343, name: "Ruxmaniben Deepchand Gardi Medical College, Ujjain", state: "Madhya Pradesh" },
  { id: 344, name: "School of Medical Sciences, Sri Satya Sai University of Technology and Medical Sciences", state: "Madhya Pradesh" },
  { id: 345, name: "Shyam Shah Medical College, Rewa", state: "Madhya Pradesh" },
  { id: 346, name: "Sri Aurobindo Medical College and Post Graduate Institute , Indore", state: "Madhya Pradesh" },
  { id: 347, name: "Sukh Sagar Medical College & Hospital, Jabalpur", state: "Madhya Pradesh" },
  { id: 348, name: "Sundarlal Patwa Govt. Medical College", state: "Madhya Pradesh" },
  { id: 349, name: "Virendra Kumar Sakhlecha Government Medical College", state: "Madhya Pradesh" },
  { id: 350, name: "All India Institute of Medical Sciences, Nagpur", state: "Maharashtra" },
  { id: 351, name: "ACPM Medical College, Dhule", state: "Maharashtra" },
  { id: 352, name: "Armed Forces Medical College, Pune", state: "Maharashtra" },
  { id: 353, name: "Ashwini Rural Medical College, Hospital & Research Centre, Solapur", state: "Maharashtra" },
  { id: 354, name: "B. J. Govt. Medical College, Pune", state: "Maharashtra" },
  { id: 355, name: "B.K.L. Walawalkar Rural Medical College, Ratnagiri", state: "Maharashtra" },
  { id: 356, name: "Bharati Vidyapeeth Deemed University Medical College & Hospital, Sangli", state: "Maharashtra" },
  { id: 357, name: "Bharati Vidyapeeth University Medical College, Pune", state: "Maharashtra" },
  { id: 358, name: "Bharatratna Atal Bihari Vajpayee Medical College, Pune", state: "Maharashtra" },
  { id: 359, name: "Datta Meghe Medical College, Nagpur", state: "Maharashtra" },
  { id: 360, name: "Dr Vaishampayan Memorial Medical College, Solapur", state: "Maharashtra" },
  { id: 361, name: "Dr. D Y Patil Medical College, Hospital and Research Centre, Pimpri, Pune", state: "Maharashtra" },
  { id: 362, name: "Dr. D Y Patil Medical College, Kolhapur", state: "Maharashtra" },
  { id: 363, name: "Dr. N Y Tasgaonkar Institute of Medical Science", state: "Maharashtra" },
  { id: 364, name: "Dr. Panjabrao Alias Bhausaheb Deshmukh Memorial Medical College, Amravati", state: "Maharashtra" },
  { id: 365, name: "Dr. Rajendra Gode Medical College, Amravati", state: "Maharashtra" },
  { id: 366, name: "Dr. Shankarrao Chavan Govt. Medical College, Nanded", state: "Maharashtra" },
  { id: 367, name: "Dr. Ulhas Patil Medical College & Hospital, Jalgaon", state: "Maharashtra" },
  { id: 368, name: "Dr. Vasantrao Pawar Med. Col. Hosp. & Research Centre, Nasik (Prev. NDMVP Samaj Medical College)", state: "Maharashtra" },
  { id: 369, name: "Dr. Vithalrao Vikhe Patil Foundations Medical College & Hospital, Ahmednagar", state: "Maharashtra" },
  { id: 370, name: "DY Patil University, School of Medicine", state: "Maharashtra" },
  { id: 371, name: "ESIC MEDICAL COLLEGE AND HOSPITAL, ANDHERI", state: "Maharashtra" },
  { id: 372, name: "Government Medical College & Hospital, Baramati", state: "Maharashtra" },
  { id: 373, name: "Government Medical college and District Hospital, Ratnagiri", state: "Maharashtra" },
  { id: 374, name: "Government Medical College L.T. Marg, Near L.T. Marg Police Station, Mumbai - 400001", state: "Maharashtra" },
  { id: 375, name: "Government Medical College, Akola", state: "Maharashtra" },
  { id: 376, name: "Government Medical College, Alibag", state: "Maharashtra" },
  { id: 377, name: "Government Medical College, Ambernath", state: "Maharashtra" },
  { id: 378, name: "Government Medical College, Amravati", state: "Maharashtra" },
  { id: 379, name: "Government Medical College, Aurangabad", state: "Maharashtra" },
  { id: 380, name: "Government Medical College, Bhandara", state: "Maharashtra" },
  { id: 381, name: "Government Medical College, Buldhana", state: "Maharashtra" },
  { id: 382, name: "Government Medical College, Chandrapur", state: "Maharashtra" },
  { id: 383, name: "Government Medical College, Gadchiroli", state: "Maharashtra" },
  { id: 384, name: "Government Medical College, Gondia", state: "Maharashtra" },
  { id: 385, name: "Government Medical College, Hingoli", state: "Maharashtra" },
  { id: 386, name: "Government Medical College, Jalgaon", state: "Maharashtra" },
  { id: 387, name: "Government Medical College, Jalna", state: "Maharashtra" },
  { id: 388, name: "Government Medical College, Latur", state: "Maharashtra" },
  { id: 389, name: "Government Medical College, Miraj", state: "Maharashtra" },
  { id: 390, name: "Government Medical College, Nagpur", state: "Maharashtra" },
  { id: 391, name: "Government Medical College, Nandurbar", state: "Maharashtra" },
  { id: 392, name: "Government Medical College, Osmanabad", state: "Maharashtra" },
  { id: 393, name: "Government Medical College, Parbhani", state: "Maharashtra" },
  { id: 394, name: "Government Medical College, Satara", state: "Maharashtra" },
  { id: 395, name: "Government Medical College, Sindhudurg", state: "Maharashtra" },
  { id: 396, name: "Government Medical College, Washim", state: "Maharashtra" },
  { id: 397, name: "Government Medical College,Nashik", state: "Maharashtra" },
  { id: 398, name: "Grant Medical College, Mumbai", state: "Maharashtra" },
  { id: 399, name: "H.B.T. Medical College & Dr. R.N. Cooper Municipal General Hospital, Juhu, Mumbai", state: "Maharashtra" },
  { id: 400, name: "Indian Institute of Medical Science & Research, Jalna", state: "Maharashtra" },
  { id: 401, name: "Indira Gandhi Medical College & Hospital, Nagpur", state: "Maharashtra" },
  { id: 402, name: "Jawaharlal Nehru Medical College, Sawangi (Meghe), Wardha", state: "Maharashtra" },
  { id: 403, name: "KJ Somaiyya Medical College & Research Centre, Mumbai", state: "Maharashtra" },
  { id: 404, name: "Krishna Institute of Medical Sciences, Karad", state: "Maharashtra" },
  { id: 405, name: "Lokmanya Tilak Municipal Medical College, Sion, Mumbai", state: "Maharashtra" },
  { id: 406, name: "Maharashtra Institute of Medical Education & Research, Talegaon, Pune", state: "Maharashtra" },
  { id: 407, name: "Maharashtra Institute of Medical Sciences & Research, Latur", state: "Maharashtra" },
  { id: 408, name: "Mahatma Gandhi Institute of Medical Sciences, Sevagram, Wardha", state: "Maharashtra" },
  { id: 409, name: "Mahatma Gandhi Mission Medical College, Vashi", state: "Maharashtra" },
  { id: 410, name: "Mahatma Gandhi Missions Medical College, Aurangabad", state: "Maharashtra" },
  { id: 411, name: "Mahatma Gandhi Missions Medical College, Navi Mumbai", state: "Maharashtra" },
  { id: 412, name: "Mahatma Gandhi Missions Medical College, Nerul, Navi Mumbai", state: "Maharashtra" },
  { id: 413, name: "Mahatma Gandhi Missions Medical College, Panvel", state: "Maharashtra" },
  { id: 414, name: "MALATI MULTISPECIALITY HOSPITAL AND MEDICAL COLLEGE", state: "Maharashtra" },
  { id: 415, name: "N. K. P. Salve Instt. of Medical Sciences and Research Centre and Lata Mangeshkar Hospital, Nagpur", state: "Maharashtra" },
  { id: 416, name: "Padmashree Dr. D.Y.Patil Medical College, Navi Mumbai", state: "Maharashtra" },
  { id: 417, name: "Parbhani Medical College", state: "Maharashtra" },
  { id: 418, name: "Prakash Institute of Medical Sciences & Research, Sangli", state: "Maharashtra" },
  { id: 419, name: "Rajashree Chatrapati Shahu Maharaj Government Medical College, Kolhapur", state: "Maharashtra" },
  { id: 420, name: "Rajiv Gandhi Medical College and Chhatrapati Shivaji Maharaj Hospital, Thane", state: "Maharashtra" },
  { id: 421, name: "R K Damani Medical College ShriRamchandra Institute of Medical Sciences, Chhatrapati Sambhajinagar", state: "Maharashtra" },
  { id: 422, name: "Rural Medical College, Loni", state: "Maharashtra" },
  { id: 423, name: "Seth GS Medical College, Mumbai", state: "Maharashtra" },
  { id: 424, name: "Shri Vasant Rao Naik Govt. Medical College, Yavatmal", state: "Maharashtra" },
  { id: 425, name: "Sindhudurg Shikshan Prasarak Mandal (SSPM) Medical College & Lifetime Hospital, Padave, Sindhudurg", state: "Maharashtra" },
  { id: 426, name: "SMBT Institute of Medical Sciences & Research Centre, Nandihills, Nashik", state: "Maharashtra" },
  { id: 427, name: "Smt Sakhubai Narayanrao Katkade Medical College and Research Center", state: "Maharashtra" },
  { id: 428, name: "Smt. Kashibai Navale Medical College and General Hospital, Pune", state: "Maharashtra" },
  { id: 429, name: "Sri Bhausaheb Hire Government Medical College, Dhule", state: "Maharashtra" },
  { id: 430, name: "SRTR Medical College, Ambajogai", state: "Maharashtra" },
  { id: 431, name: "Symbiosis Medical College for Women, Pune", state: "Maharashtra" },
  { id: 432, name: "Terna Medical College, Navi Mumbai", state: "Maharashtra" },
  { id: 433, name: "Topiwala National Medical College, Mumbai", state: "Maharashtra" },
  { id: 434, name: "Vedantaa Institute of Medical Sciences, Palghar, Maharashtra", state: "Maharashtra" },
  { id: 435, name: "Government Medical College, Churachandpur", state: "Manipur" },
  { id: 436, name: "Jawaharlal Nehru Institute of Medical Sciences, Porompet, Imphal", state: "Manipur" },
  { id: 437, name: "Regional Institute of Medical Sciences, Imphal", state: "Manipur" },
  { id: 438, name: "Shija Academy of Health Sciences", state: "Manipur" },
  { id: 439, name: "North Eastern Indira Gandhi Regional Instt. of Health and Medical Sciences, Shillong", state: "Meghalaya" },
  { id: 440, name: "PA Sangama International Medical College and Hospital", state: "Meghalaya" },
  { id: 441, name: "Shillong Medical College", state: "Meghalaya" },
  { id: 442, name: "Zoram Medical College, Mizoram", state: "Mizoram" },
  { id: 443, name: "Nagaland Institute of Medical Sciences & Research", state: "Nagaland" },
  { id: 444, name: "All India Institute of Medical Sciences, Bhubaneswar", state: "Orissa" },
  { id: 445, name: "Government Medical College & Hospital (Renamed as Bhima Bhoi Medical College & Hospital), Balangir", state: "Orissa" },
  { id: 446, name: "DRIEMS Institute of Health Sciences and Hospital, Kairapari", state: "Orissa" },
  { id: 447, name: "Government Medical College & Hospital (Renamed as Fakir Mohan Medical College & Hospital), Balasore", state: "Orissa" },
  { id: 448, name: "GOVERNMENT MEDICAL COLLEGE PHULBANI , KANDHAMAL", state: "Orissa" },
  { id: 449, name: "Saheed Rendo Majhi Medical College and Hospital, Bhawanipatna, Kalahandi, Odisha (erstwhile Government Medical College, Bhawanipatna)", state: "Orissa" },
  { id: 450, name: "Dharanidhar Medical College and Hospital (previously Government Medical College, Keonjhar)", state: "Orissa" },
  { id: 451, name: "Government Medical College, Sundargarh", state: "Orissa" },
  { id: 452, name: "Hi-Tech Medical College & Hospital, Bhubaneswar", state: "Orissa" },
  { id: 453, name: "Hi-Tech Medical College & Hospital, Rourkela", state: "Orissa" },
  { id: 454, name: "Institute of Medical Sciences and SUM Hospital, Campus-II, Phulnakhara, Bhubaneswar", state: "Orissa" },
  { id: 455, name: "Institute Of Medical Sciences & SUM Hospital, Bhubaneswar", state: "Orissa" },
  { id: 456, name: "Kalinga Institute of Medical Sciences, Bhubaneswar", state: "Orissa" },
  { id: 457, name: "Mahraja Jajati Keshari Medical College (previously Government Medical College and Hospital, Jajpur Odhisha)", state: "Orissa" },
  { id: 458, name: "MKCG Medical College, Berhampur", state: "Orissa" },
  { id: 459, name: "PABITRA MOHAN PRADHAN MEDICAL COLLEGE, TALCHER", state: "Orissa" },
  { id: 460, name: "Pt. Raghunath Murmu Medical College and Hospital, Baripada, Odisha", state: "Orissa" },
  { id: 461, name: "Saheed Laxman Nayak Medical College & Hospital, Koraput", state: "Orissa" },
  { id: 462, name: "SCB Medical College, Cuttack", state: "Orissa" },
  { id: 463, name: "Sri Jagannath Medical College & Hospital, Puri", state: "Orissa" },
  { id: 464, name: "Veer Surendra Sai Institute of Medical Sciences and Research, Burla", state: "Orissa" },
  { id: 465, name: "Jawaharlal Institute of Postgraduate Medical Education & Research, Puducherry", state: "Pondicherry" },
  { id: 466, name: "Aarupadai Veedu Medical College, Pondicherry", state: "Pondicherry" },
  { id: 467, name: "Indira Gandhi Medical College & Research Institute, Puducherry", state: "Pondicherry" },
  { id: 468, name: "Mahatma Gandhi Medical College & Research Institute, Pondicherry", state: "Pondicherry" },
  { id: 469, name: "Puducherry Institute of Medical Sciences & Research, Pondicherry", state: "Pondicherry" },
  { id: 470, name: "Sri Lakshmi Narayana Institute of Medical Sciences, Pondicherry", state: "Pondicherry" },
  { id: 471, name: "Sri Manakula Vinayagar Medical College & Hospital, Pondicherry", state: "Pondicherry" },
  { id: 472, name: "Sri Venkateswaraa Medical College, Hospital & Research Centre, Pondicherry", state: "Pondicherry" },
  { id: 473, name: "Vinayaka Missions Medical College, Karaikal, Pondicherry", state: "Pondicherry" },
  { id: 474, name: "All India Institute of Medical Sciences, Bathinda", state: "Punjab" },
  { id: 475, name: "Chintpurni Medical College, Pathankot, Gurdaspur", state: "Punjab" },
  { id: 476, name: "Adesh Institute of Medical Sciences & Research, Bhatinda", state: "Punjab" },
  { id: 477, name: "Christian Medical College, Ludhiana", state: "Punjab" },
  { id: 478, name: "Dayanand Medical College & Hospital, Ludhiana", state: "Punjab" },
  { id: 479, name: "Dr B R Ambedkar State Institute of Medical Sciences, SAS Nagar , Mohali", state: "Punjab" },
  { id: 480, name: "ESIC Medical College Ludhiana", state: "Punjab" },
  { id: 481, name: "Gian Sagar Medical College & Hospital, Patiala", state: "Punjab" },
  { id: 482, name: "Government Medical College, Amritsar", state: "Punjab" },
  { id: 483, name: "Government Medical College, Patiala", state: "Punjab" },
  { id: 484, name: "Guru Govind Singh Medical College, Faridkot", state: "Punjab" },
  { id: 485, name: "Punjab Institute of Medical Sciences, Jalandhar", state: "Punjab" },
  { id: 486, name: "RIMT Medical College and Hospital", state: "Punjab" },
  { id: 487, name: "Sri Guru Ram Das Institute of Medical Sciences and Research, Sri Amritsar", state: "Punjab" },
  { id: 488, name: "All India Institute of Medical Sciences, Jodhpur", state: "Rajasthan" },
  { id: 489, name: "Government Medical College, Sawai Madhopur", state: "Rajasthan" },
  { id: 490, name: "American International Institute of Medical Sciences, Bedwas", state: "Rajasthan" },
  { id: 491, name: "Ananta Institute of Medical Sciences & Research Centre, Rajsamand", state: "Rajasthan" },
  { id: 492, name: "Arya Medical College and Hospital", state: "Rajasthan" },
  { id: 493, name: "Balvir Singh Tomar Institute of Medical Sciences and Research", state: "Rajasthan" },
  { id: 494, name: "Dr S S Tantia Medical College Hospital & Research Centre", state: "Rajasthan" },
  { id: 495, name: "Dr SN Medical College, Jodhpur", state: "Rajasthan" },
  { id: 496, name: "Employees State Insurance Corporation Medical College,Alwar", state: "Rajasthan" },
  { id: 497, name: "ESIC MEDICAL COLLEGE AND HOSPITAL, JAIPUR", state: "Rajasthan" },
  { id: 498, name: "GEETANJALI INSTITUTE OF MEDICAL SCIENCES", state: "Rajasthan" },
  { id: 499, name: "Geetanjali Medical College & Hospital,Udaipur", state: "Rajasthan" },
  { id: 500, name: "Government Medical College, Alwar", state: "Rajasthan" },
  { id: 501, name: "Government Medical College, Banswara", state: "Rajasthan" },
  { id: 502, name: "Government Medical College, Baran", state: "Rajasthan" },
  { id: 503, name: "Government Medical College, Barmer", state: "Rajasthan" },
  { id: 504, name: "Government Medical College, Bharatpur, Rajasthan", state: "Rajasthan" },
  { id: 505, name: "Government Medical College, Bhilwara, Rajasthan", state: "Rajasthan" },
  { id: 506, name: "Government Medical College, Bundi", state: "Rajasthan" },
  { id: 507, name: "Government Medical College, Chittorgarh", state: "Rajasthan" },
  { id: 508, name: "Government Medical College, Churu", state: "Rajasthan" },
  { id: 509, name: "Government Medical College, Dausa", state: "Rajasthan" },
  { id: 510, name: "Government Medical College, Dholpur", state: "Rajasthan" },
  { id: 511, name: "Government Medical College, Dungarpur", state: "Rajasthan" },
  { id: 512, name: "Government Medical College, Hanumangarh", state: "Rajasthan" },
  { id: 513, name: "Government Medical College, Jaisalmer", state: "Rajasthan" },
  { id: 514, name: "Government Medical College, Jhunjhunu", state: "Rajasthan" },
  { id: 515, name: "Government Medical College, Karauli", state: "Rajasthan" },
  { id: 516, name: "Government Medical College, Kota", state: "Rajasthan" },
  { id: 517, name: "Government Medical College, Nagaur", state: "Rajasthan" },
  { id: 518, name: "Government Medical College, Pali, Rajasthan", state: "Rajasthan" },
  { id: 519, name: "Government Medical College, Sirohi", state: "Rajasthan" },
  { id: 520, name: "Government Medical College, Sri Ganganagar", state: "Rajasthan" },
  { id: 521, name: "Government medical college, tonk", state: "Rajasthan" },
  { id: 522, name: "Jaipur National University Institute for Medical Sciences and Research Centre, Jagatpura, Jaipur", state: "Rajasthan" },
  { id: 523, name: "Jawaharlal Nehru Medical College, Ajmer", state: "Rajasthan" },
  { id: 524, name: "Jhalawar Medical College, Jhalawar", state: "Rajasthan" },
  { id: 525, name: "JIET Medical College and Hospital", state: "Rajasthan" },
  { id: 526, name: "Mahatma Gandhi Medical College and Hospital, Sitapur, Jaipur", state: "Rajasthan" },
  { id: 527, name: "National Institute of Medical Science & Research, Jaipur", state: "Rajasthan" },
  { id: 528, name: "Pacific Institute of Medical Sciences, Umarda, Udaipur", state: "Rajasthan" },
  { id: 529, name: "Pacific Medical College & Hospital, Bhilo Ka Bedla, Udaipur", state: "Rajasthan" },
  { id: 530, name: "R N T Medical College, Udaipur", state: "Rajasthan" },
  { id: 531, name: "RUHS College of Medical Sciences, Jaipur", state: "Rajasthan" },
  { id: 532, name: "Sardar Patel Medical College, Bikaner", state: "Rajasthan" },
  { id: 533, name: "Shri Kalyan Govt. Medical College, Sikar, Rajasthan", state: "Rajasthan" },
  { id: 534, name: "SMS Medical College, Jaipur", state: "Rajasthan" },
  { id: 535, name: "Sudha Medical College, Kota, Rajasthan", state: "Rajasthan" },
  { id: 536, name: "Vyas Medical College & Hospital Jodhpur, Rajasthan", state: "Rajasthan" },
  { id: 537, name: "Sikkim Manipal Institute of Medical Sciences, Gangtok", state: "Sikkim" },
  { id: 538, name: "All India Institute of Medical Sciences, Madurai", state: "Tamil Nadu" },
  { id: 539, name: "ACS Medical College and Hospital, Chennai", state: "Tamil Nadu" },
  { id: 540, name: "Rajalakshmi Medical College Hospital and Research Institute", state: "Tamil Nadu" },
  { id: 541, name: "Annapoorna Medical College & Hospital, Salem", state: "Tamil Nadu" },
  { id: 542, name: "Arunai Medical College And Hospital", state: "Tamil Nadu" },
  { id: 543, name: "Bhaarat Medical College & Hospital", state: "Tamil Nadu" },
  { id: 544, name: "Chengalpattu Medical College, Chengalpattu", state: "Tamil Nadu" },
  { id: 545, name: "Chettinad Hospital & Research Institute, Kanchipuram", state: "Tamil Nadu" },
  { id: 546, name: "Christian Medical College, Vellore", state: "Tamil Nadu" },
  { id: 547, name: "Coimbatore Medical College, Coimbatore", state: "Tamil Nadu" },
  { id: 548, name: "Dhanalakshmi Srinivasan Institute of Medical Sciences and Hospital - Thuraiyur Road, Perambalur", state: "Tamil Nadu" },
  { id: 549, name: "Dhanalakshmi Srinivasan Medical College and Hospital, Perambalur", state: "Tamil Nadu" },
  { id: 550, name: "ESIC Medical College & PGIMSR, K.K Nagar, Chennai", state: "Tamil Nadu" },
  { id: 551, name: "Faculty of Medicine , Sri Lalithambigai Medical College and Hospital", state: "Tamil Nadu" },
  { id: 552, name: "Government Dharmapuri Medical College, Dharmapuri", state: "Tamil Nadu" },
  { id: 553, name: "Government Erode Medical College & Hospital, Perundurai (Formerly IRT Perundurai Medical College)", state: "Tamil Nadu" },
  { id: 554, name: "Government Medical College & ESIC Hospital, Coimbatore, Tamil Nadu.", state: "Tamil Nadu" },
  { id: 555, name: "Government Medical College, Ariyalur", state: "Tamil Nadu" },
  { id: 556, name: "Government Medical College, Dindigul", state: "Tamil Nadu" },
  { id: 557, name: "Government Medical College, Kallakurichi", state: "Tamil Nadu" },
  { id: 558, name: "Government Medical College, Karur", state: "Tamil Nadu" },
  { id: 559, name: "Government Medical College, Krishnagiri", state: "Tamil Nadu" },
  { id: 560, name: "Government Medical College, Nagapattinam", state: "Tamil Nadu" },
  { id: 561, name: "Government Medical College, Namakkal", state: "Tamil Nadu" },
  { id: 562, name: "Government Medical College, Omandurar", state: "Tamil Nadu" },
  { id: 563, name: "Government Medical College, Pudukottai, Tamil Nadu", state: "Tamil Nadu" },
  { id: 564, name: "Government Medical College, Ramanathapuram", state: "Tamil Nadu" },
  { id: 565, name: "Government Medical College, The Nilgiris", state: "Tamil Nadu" },
  { id: 566, name: "Government Medical College, Thiruvallur", state: "Tamil Nadu" },
  { id: 567, name: "Government Medical College, Tiruppur", state: "Tamil Nadu" },
  { id: 568, name: "Government Medical College, Virudhunagar", state: "Tamil Nadu" },
  { id: 569, name: "Government Sivagangai Medical College, Sivaganga", state: "Tamil Nadu" },
  { id: 570, name: "Government Thiruvannamalai Medical College, Thiruvannamalai", state: "Tamil Nadu" },
  { id: 571, name: "Government Vellore Medical College, Vellore", state: "Tamil Nadu" },
  { id: 572, name: "Government Villupuram Medical College, Villupuram", state: "Tamil Nadu" },
  { id: 573, name: "Govt. Mohan Kumaramangalam Medical College, Salem", state: "Tamil Nadu" },
  { id: 574, name: "Indira Medical College & Hospitals, Thiruvallur", state: "Tamil Nadu" },
  { id: 575, name: "J R Medical College and Hospital Villupuram District, Tamilnadu", state: "Tamil Nadu" },
  { id: 576, name: "K A P Viswanathan Government Medical College, Trichy", state: "Tamil Nadu" },
  { id: 577, name: "KanyaKumari Government Medical College, Asaripallam", state: "Tamil Nadu" },
  { id: 578, name: "Kanyakumari Medical Mission Research Centre, Kanyakumari District", state: "Tamil Nadu" },
  { id: 579, name: "Karpaga Vinayaga Institute of Medical Sciences, Maduranthagam", state: "Tamil Nadu" },
  { id: 580, name: "Karpagam Faculty of Medical Sciences & Research, Coimbatore", state: "Tamil Nadu" },
  { id: 581, name: "Kilpauk Medical College, Chennai", state: "Tamil Nadu" },
  { id: 582, name: "KMCH Institute of Health Sciences and Research, Coimbatore", state: "Tamil Nadu" },
  { id: 583, name: "Madha Medical College and Hospital, Thandalam, Chennai", state: "Tamil Nadu" },
  { id: 584, name: "Madras Medical College, Chennai", state: "Tamil Nadu" },
  { id: 585, name: "Madurai Medical College, Madurai", state: "Tamil Nadu" },
  { id: 586, name: "Meenakshi Medical College and Research Institute, Enathur", state: "Tamil Nadu" },
  { id: 587, name: "Melmaruvathur Adiparasakthi Instt. Medical Sciences and Research", state: "Tamil Nadu" },
  { id: 588, name: "Nandha Medical College & Hospital Erode", state: "Tamil Nadu" },
  { id: 589, name: "Panimalar Medical College Hospital & Research Institute, Chennai,Tamil Nadu", state: "Tamil Nadu" },
  { id: 590, name: "PSG Institute of Medical Sciences, Coimbatore", state: "Tamil Nadu" },
  { id: 591, name: "PSP Medical College Hospital and Research Institute, Chennai", state: "Tamil Nadu" },
  { id: 592, name: "Government Medical College & Hospital Cuddalore, Since- 09-05-2025 (erstwhile Rajah Muthiah Medical College, cuddalore, T.N)", state: "Tamil Nadu" },
  { id: 593, name: "Saveetha Medical College and Hospital, Kanchipuram", state: "Tamil Nadu" },
  { id: 594, name: "Shri Sathya Sai Medical College and Research Institute, Kancheepuram", state: "Tamil Nadu" },
  { id: 595, name: "Sree Balaji Medical College and Hospital, Chennai", state: "Tamil Nadu" },
  { id: 596, name: "Sree Mookambika Institute of Medical Sciences, Kanyakumari", state: "Tamil Nadu" },
  { id: 597, name: "Sri Muthukumaran Medical College,Chennai", state: "Tamil Nadu" },
  { id: 598, name: "Sri Ramachandra Medical College & Research Institute, Chennai", state: "Tamil Nadu" },
  { id: 599, name: "Sri Venkateswaraa Medical College Hospital and Research Institute, Chennai", state: "Tamil Nadu" },
  { id: 600, name: "Srinivasan Medical College and Hospital", state: "Tamil Nadu" },
  { id: 601, name: "SRM Medical College Hospital & Research Centre, Kancheepuram", state: "Tamil Nadu" },
  { id: 602, name: "ST Peters Medical College, Hospital & Research Institute", state: "Tamil Nadu" },
  { id: 603, name: "Stanley Medical College, Chennai", state: "Tamil Nadu" },
  { id: 604, name: "Swamy Vivekanandha Medical College Hospital And Research Institute", state: "Tamil Nadu" },
  { id: 605, name: "Tagore Medical College and Hospital, Chennai", state: "Tamil Nadu" },
  { id: 606, name: "TAKSHASHILA MEDICAL COLLEGE", state: "Tamil Nadu" },
  { id: 607, name: "Thanjavur Medical College, Thanjavur", state: "Tamil Nadu" },
  { id: 608, name: "Theni Government Medical College, Theni", state: "Tamil Nadu" },
  { id: 609, name: "Thiruvarur Govt. Medical College, Thiruvarur", state: "Tamil Nadu" },
  { id: 610, name: "Thoothukudi Medical College, Thoothukudi", state: "Tamil Nadu" },
  { id: 611, name: "Tirunelveli Medical College, Tirunelveli", state: "Tamil Nadu" },
  { id: 612, name: "Trichy SRM Medical College Hospital & Research Centre, Trichy", state: "Tamil Nadu" },
  { id: 613, name: "Velammal Medical College Hospital and Research Institute, Madurai", state: "Tamil Nadu" },
  { id: 614, name: "VELS Medical College & Hospital", state: "Tamil Nadu" },
  { id: 615, name: "Vinayaka Missions Kirupananda Variyar Medical College, Salem", state: "Tamil Nadu" },
  { id: 616, name: "All India Institute of Medical Sciences, Bibinagar", state: "Telangana" },
  { id: 617, name: "Apollo Institute of Medical Sciences and Research, Hyderabad", state: "Telangana" },
  { id: 618, name: "Arundathi Institute of Medical Sciences, Medchal", state: "Telangana" },
  { id: 619, name: "Government Medical College, Yadadri", state: "Telangana" },
  { id: 620, name: "Ayaan Institute of Medical Sciences, Teaching Hospital & Research Centre, Kanaka Mamidi, R.R. Dist", state: "Telangana" },
  { id: 621, name: "Bhaskar Medical College, Yenkapally", state: "Telangana" },
  { id: 622, name: "Chalmeda Anand Rao Institute Of Medical Sciences, Karimnagar", state: "Telangana" },
  { id: 623, name: "CMR Institute of Medical Science", state: "Telangana" },
  { id: 624, name: "Deccan College of Medical Sciences", state: "Telangana" },
  { id: 625, name: "Dr. Patnam Mahender Reddy Institute of Medical Sciences, Chevella, Rangareddy", state: "Telangana" },
  { id: 626, name: "Dr. VRK Womens Medical College, Aziznagar", state: "Telangana" },
  { id: 627, name: "Employees State Insurance Coporation Medical College, Sanath Nagar, Hyderabad", state: "Telangana" },
  { id: 628, name: "Father Colombo Institute of Medical Sciences, Warangal", state: "Telangana" },
  { id: 629, name: "Gandhi Medical College, Secunderabad", state: "Telangana" },
  { id: 630, name: "GOVERNMENT MEDICAL COLLEGE JANGAON", state: "Telangana" },
  { id: 631, name: "GOVERNMENT MEDICAL COLLEGE KHAMMAM", state: "Telangana" },
  { id: 632, name: "GOVERNMENT MEDICAL COLLEGE KUMURAM BHEEM ASIFAFABAD", state: "Telangana" },
  { id: 633, name: "Government Medical College Medak", state: "Telangana" },
  { id: 634, name: "GOVERNMENT MEDICAL COLLEGE VIKARABAD", state: "Telangana" },
  { id: 635, name: "Government Medical College, Bhadradri Kothagudem", state: "Telangana" },
  { id: 636, name: "Government Medical College, Jagtial", state: "Telangana" },
  { id: 637, name: "Government Medical College, Jayashankar Bhupalpally", state: "Telangana" },
  { id: 638, name: "Government Medical College, Jogulumba Gadwal", state: "Telangana" },
  { id: 639, name: "Government Medical College, Kamareddy", state: "Telangana" },
  { id: 640, name: "Government Medical College, Karimnagar", state: "Telangana" },
  { id: 641, name: "GOVERNMENT MEDICAL COLLEGE, KODANGAL", state: "Telangana" },
  { id: 642, name: "Government Medical College, Mahabubabad", state: "Telangana" },
  { id: 643, name: "Government Medical College, Mahabubnagar", state: "Telangana" },
  { id: 644, name: "Government Medical College, Maheshwaram", state: "Telangana" },
  { id: 645, name: "Government Medical College, Mancherial", state: "Telangana" },
  { id: 646, name: "Government Medical College, Mulugu", state: "Telangana" },
  { id: 647, name: "Government Medical College, Nagarkurnool", state: "Telangana" },
  { id: 648, name: "Government Medical College, Nalgonda", state: "Telangana" },
  { id: 649, name: "Government Medical College, Narayanpet", state: "Telangana" },
  { id: 650, name: "Government Medical College, Narsampet", state: "Telangana" },
  { id: 651, name: "Government Medical College, Nirmal", state: "Telangana" },
  { id: 652, name: "Government Medical College, Nizamabad", state: "Telangana" },
  { id: 653, name: "Government medical College, Quthbullapur", state: "Telangana" },
  { id: 654, name: "Government Medical College, Rajanna Sircilla", state: "Telangana" },
  { id: 655, name: "Government Medical College, Ramagundam", state: "Telangana" },
  { id: 656, name: "Government Medical College, Sangareddy", state: "Telangana" },
  { id: 657, name: "Government Medical College, Siddipet", state: "Telangana" },
  { id: 658, name: "Government Medical College, Suryapet", state: "Telangana" },
  { id: 659, name: "Government Medical College, Wanaparthy", state: "Telangana" },
  { id: 660, name: "Kakatiya Medical College, Warangal", state: "Telangana" },
  { id: 661, name: "Kamineni Academy of Medical Sciences & Research Center, Hyderabad", state: "Telangana" },
  { id: 662, name: "Kamineni Institute of Medical Sciences, Narketpally", state: "Telangana" },
  { id: 663, name: "Mahavir Institute of Medical Sciences, Vikarabad, Telengana", state: "Telangana" },
  { id: 664, name: "Maheshwara Medical College, Chitkul, Patancheru, Medak", state: "Telangana" },
  { id: 665, name: "Malla Reddy Institute of Medical Sciences, Hyderabad", state: "Telangana" },
  { id: 666, name: "Mallareddy Medical College for Women, Hyderabad", state: "Telangana" },
  { id: 667, name: "Mamata Academy of Medical Sciences, Bachupally", state: "Telangana" },
  { id: 668, name: "Mamata Medical College, Khammam", state: "Telangana" },
  { id: 669, name: "Mediciti Institute Of Medical Sciences, Ghanpur", state: "Telangana" },
  { id: 670, name: "MNR Medical College & Hospital, Sangareddy", state: "Telangana" },
  { id: 671, name: "NEELIMA INSTITUTE OF MEDICAL SCIENCES", state: "Telangana" },
  { id: 672, name: "Nova Institute of Medical Sciences and Research Centre", state: "Telangana" },
  { id: 673, name: "Osmania Medical College, Hyderabad", state: "Telangana" },
  { id: 674, name: "Prathima Institute Of Medical Sciences, Karimnagar", state: "Telangana" },
  { id: 675, name: "Prathima Relief Institute of Medical Sciences, Warangal", state: "Telangana" },
  { id: 676, name: "R.V.M. Institute of Medical Sciences and Research Centre, Siddipet", state: "Telangana" },
  { id: 677, name: "Rajiv Gandhi Institute of Medical Sciences, adilabad", state: "Telangana" },
  { id: 678, name: "S V S Medical College, Mehboobnagar", state: "Telangana" },
  { id: 679, name: "Shadan Institute of Medical Sciences,Research Centre and Teaching Hospital, Peerancheru", state: "Telangana" },
  { id: 680, name: "Surabhi Institute of Medical Sciences, Siddipet, Telangana", state: "Telangana" },
  { id: 681, name: "TRR Institute of Medical Sciences, patancheru", state: "Telangana" },
  { id: 682, name: "Agartala Government Medical College,Agartala", state: "Tripura" },
  { id: 683, name: "Tripura Medical College and Dr. B R A M Teaching Hospital, Agartala", state: "Tripura" },
  { id: 684, name: "Tripura Santiniketan Medical College, Dist- West Tripura", state: "Tripura" },
  { id: 685, name: "All India Institute of Medical Sciences, Rishikesh", state: "Uttarakhand" },
  { id: 686, name: "Doon Medical College, Dehradun, Uttarakhand", state: "Uttarakhand" },
  { id: 687, name: "Gautam Buddha Chikitsa Mahavidyalaya, Dehradum", state: "Uttarakhand" },
  { id: 688, name: "Government Medical College (Prev.Uttarakhand Forest Hospital Trust Med.Col.), Haldwani", state: "Uttarakhand" },
  { id: 689, name: "Government Medical College, Haridwar", state: "Uttarakhand" },
  { id: 690, name: "Graphic Era Institute of Medical Sciences Dehradun, Uttrakhand", state: "Uttarakhand" },
  { id: 691, name: "Himalayan Institute of Medical Sciences, Dehradun", state: "Uttarakhand" },
  { id: 692, name: "Shri Guru Ram Rai Institute of Medical & Health Sciences, Dehradun", state: "Uttarakhand" },
  { id: 693, name: "Soban Singh jeena Government institute of Medical science & Research, Almora", state: "Uttarakhand" },
  { id: 694, name: "Veer Chandra Singh Garhwali Govt. Medical Sc. & Research Instt, Srinagar, Pauri Garhwal", state: "Uttarakhand" },
  { id: 695, name: "All India Institute of Medical Sciences, Gorakhpur", state: "Uttar Pradesh" },
  { id: 696, name: "All India Institute of Medical Sciences, Rae Bareli", state: "Uttar Pradesh" },
  { id: 697, name: "Ajay Sangaal Institute of Medical Sciences and Ayushman Hospital Shamli (UP)", state: "Uttar Pradesh" },
  { id: 698, name: "Autonomous State Medical College Sultanpur", state: "Uttar Pradesh" },
  { id: 699, name: "Autonomous state medical college Amethi", state: "Uttar Pradesh" },
  { id: 700, name: "Punyashloka Lokmata Devi Ahilyabai Holkar Autonomous State Medical College, Auraiya (U.P.)", state: "Uttar Pradesh" },
  { id: 701, name: "Autonomous State Medical College and Hospital Gonda", state: "Uttar Pradesh" },
  { id: 702, name: "Autonomous State Medical College and Hospital Kaushambi", state: "Uttar Pradesh" },
  { id: 703, name: "Autonomous State Medical College and Hospital Lakhimpuri kheri", state: "Uttar Pradesh" },
  { id: 704, name: "Autonomous State Medical College Kushinagar", state: "Uttar Pradesh" },
  { id: 705, name: "Autonomous State Medical College Lalitpur", state: "Uttar Pradesh" },
  { id: 706, name: "Autonomous State Medical College Pilibhit", state: "Uttar Pradesh" },
  { id: 707, name: "Autonomous State Medical College Pratapgarh", state: "Uttar Pradesh" },
  { id: 708, name: "Autonomous State Medical College Society Ghazipur", state: "Uttar Pradesh" },
  { id: 709, name: "Autonomous State Medical College Society, Etah, Uttar Pradesh", state: "Uttar Pradesh" },
  { id: 710, name: "Autonomous State Medical College Society, Fatehpur", state: "Uttar Pradesh" },
  { id: 711, name: "Autonomous State Medical College Society, Hardoi", state: "Uttar Pradesh" },
  { id: 712, name: "Autonomous State Medical College, Akbarpur, Kanpur", state: "Uttar Pradesh" },
  { id: 713, name: "Autonomous State Medical College, Siddharthnagar", state: "Uttar Pradesh" },
  { id: 714, name: "Autonomous State Medical College, Sonebhadra", state: "Uttar Pradesh" },
  { id: 715, name: "Autonomous State Society Medical College Mirzapur", state: "Uttar Pradesh" },
  { id: 716, name: "Baba Kina Ram Autonomous State Medical College and Hospital Chandauli", state: "Uttar Pradesh" },
  { id: 717, name: "BRD Medical College, Gorakhpur", state: "Uttar Pradesh" },
  { id: 718, name: "Career Instt. Of Medical Sciences & Hospital, Lucknow", state: "Uttar Pradesh" },
  { id: 719, name: "Dr. B.S. Kushwah Medical College, Kanpur", state: "Uttar Pradesh" },
  { id: 720, name: "Dr. Ram Manohar Lohia Institute of Medical Sciences,Lucknow", state: "Uttar Pradesh" },
  { id: 721, name: "Era Lucknow Medical College , Lucknow", state: "Uttar Pradesh" },
  { id: 722, name: "ESIC MEDICAL COLLEGE AND HOSPITAL, NOIDA", state: "Uttar Pradesh" },
  { id: 723, name: "ESIC Medical College and Hospital, VARANASI", state: "Uttar Pradesh" },
  { id: 724, name: "F.H. Medical College & Hospital, Etamdapur, Agra", state: "Uttar Pradesh" },
  { id: 725, name: "G.S. Medical College & Hospital, Hapur, UP", state: "Uttar Pradesh" },
  { id: 726, name: "Government Allopathic Medical College, Banda, UP", state: "Uttar Pradesh" },
  { id: 727, name: "Government Institute of Medical Sciences, Kasna, Greater Noida", state: "Uttar Pradesh" },
  { id: 728, name: "Government Medical College & Super facility Hospital, Azamgarh", state: "Uttar Pradesh" },
  { id: 729, name: "Government Medical College, Badaun, U.P.", state: "Uttar Pradesh" },
  { id: 730, name: "Government Medical College, Faizabad", state: "Uttar Pradesh" },
  { id: 731, name: "Government Medical College, Firozabad", state: "Uttar Pradesh" },
  { id: 732, name: "Dr. Bhimrao Ramji Ambedkar Government Medical College, Kannauj ,Uttar Pradesh", state: "Uttar Pradesh" },
  { id: 733, name: "Government Medical College, Rampur, Basti", state: "Uttar Pradesh" },
  { id: 734, name: "Government Medical College, Shahjahanpur, UP", state: "Uttar Pradesh" },
  { id: 735, name: "GSVM Medical College, Kanpur", state: "Uttar Pradesh" },
  { id: 736, name: "Heritage Institute of Medical Sciences, Varanasi", state: "Uttar Pradesh" },
  { id: 737, name: "Hind Institute of Medical Sciences , Barabanki", state: "Uttar Pradesh" },
  { id: 738, name: "Hind Institute of Medical Sciences, Sitapur", state: "Uttar Pradesh" },
  { id: 739, name: "Institute of Medical Sciences, BHU, Varansi", state: "Uttar Pradesh" },
  { id: 740, name: "Integral Institute of Medical Sciences & Research, Lucknow", state: "Uttar Pradesh" },
  { id: 741, name: "Jawaharlal Nehru Medical College, Aligarh", state: "Uttar Pradesh" },
  { id: 742, name: "K.D. Medical College Hospital & Research Centre, Mathura", state: "Uttar Pradesh" },
  { id: 743, name: "Kalyan Singh Government Medical College", state: "Uttar Pradesh" },
  { id: 744, name: "King George Medical University, Lucknow", state: "Uttar Pradesh" },
  { id: 745, name: "KMC Medical College & Hospital, Maharajganj, Uttar Pradesh", state: "Uttar Pradesh" },
  { id: 746, name: "Krishna Mohan Medical College & Hospital, Mathura", state: "Uttar Pradesh" },
  { id: 747, name: "LLRM Medical College, Meerut", state: "Uttar Pradesh" },
  { id: 748, name: "Mahamaya Rajkiya Allopathic Medical College, Ambedkarnagar", state: "Uttar Pradesh" },
  { id: 749, name: "Maharani Laxmi Bai Medical College, Jhansi", state: "Uttar Pradesh" },
  { id: 750, name: "Maharshi Devraha Baba Autonomous State Medical College, Deoria", state: "Uttar Pradesh" },
  { id: 751, name: "Mahatma Vidur Autonomous State Medical College", state: "Uttar Pradesh" },
  { id: 752, name: "Dr. KNS Memorial Institute of Medical Sciences ( Formerly Known as Mayo Institute of Medical Sciences), Lucknow-Ayodhya Road", state: "Uttar Pradesh" },
  { id: 753, name: "Moti Lal Nehru Medical College, Allahabad", state: "Uttar Pradesh" },
  { id: 754, name: "Muzaffarnagar Medical College, Muzaffarnagar", state: "Uttar Pradesh" },
  { id: 755, name: "Naraina Medical College & Research Centre", state: "Uttar Pradesh" },
  { id: 756, name: "National Capital Region Institute of Medical Sciences, Meerut", state: "Uttar Pradesh" },
  { id: 757, name: "Noida International Institute Of Medical Sciences", state: "Uttar Pradesh" },
  { id: 758, name: "Prasad Institute of Medical Sciences, Lucknow", state: "Uttar Pradesh" },
  { id: 759, name: "Rajkiya Allopathic Medical College, Bahraich, UP", state: "Uttar Pradesh" },
  { id: 760, name: "Rajkiya Medical College Jalaun, Orai, Uttar Pradesh", state: "Uttar Pradesh" },
  { id: 761, name: "Rajshree Medical Research Institute, Bareilly", state: "Uttar Pradesh" },
  { id: 762, name: "Rama Medical College and Hospital , Kanpur", state: "Uttar Pradesh" },
  { id: 763, name: "Rama Medical College Hospital and Research Centre, Hapur", state: "Uttar Pradesh" },
  { id: 764, name: "Rohilkhand Medical College & Hospital, Bareilly", state: "Uttar Pradesh" },
  { id: 765, name: "S N Medical College, Agra", state: "Uttar Pradesh" },
  { id: 766, name: "Santosh Medical College, Ghaziabad", state: "Uttar Pradesh" },
  { id: 767, name: "Saraswati Institute of Medical Sciences, Hapur", state: "Uttar Pradesh" },
  { id: 768, name: "Saraswati Medical College, Unnao, U.P.", state: "Uttar Pradesh" },
  { id: 769, name: "Sharda School of Medical Sciences & Research ( previously School of Medical Sciences & Research,Greater Noida)", state: "Uttar Pradesh" },
  { id: 770, name: "Shaikh-UL-Hind Maulana Mahmood Hasan Medical College, Saharanpur", state: "Uttar Pradesh" },
  { id: 771, name: "Shri Gorakshnath Medical College Hospital & Arogya Dham Gorakhpur (UP)", state: "Uttar Pradesh" },
  { id: 772, name: "Shri Ram Murti Smarak Institute of Medical Sciences, Bareilly", state: "Uttar Pradesh" },
  { id: 773, name: "Shri Siddhi Vinayak Medical College & Hospital Sambhal (UP) 244302", state: "Uttar Pradesh" },
  { id: 774, name: "SKS Hospital Medical College & Research Centre", state: "Uttar Pradesh" },
  { id: 775, name: "Subharti Medical College, Meerut", state: "Uttar Pradesh" },
  { id: 776, name: "T S Misra Medical College & Hospital, Amusi, Lucknow", state: "Uttar Pradesh" },
  { id: 777, name: "Teerthanker Mahaveer Medical College, Moradabad", state: "Uttar Pradesh" },
  { id: 778, name: "Uma Nath Singh Autonomous State Medical College Society Jaunpur", state: "Uttar Pradesh" },
  { id: 779, name: "United Institute of Medical Sciences, Allahabad", state: "Uttar Pradesh" },
  { id: 780, name: "Uttar Pradesh University of Medical Sciences, (Prev. UP Rural Inst.of Med.Sc&R) Etawah", state: "Uttar Pradesh" },
  { id: 781, name: "Varun Arjun Medical College, Banthra, Shahjahanpur", state: "Uttar Pradesh" },
  { id: 782, name: "Venkateshwara Institute of Medical Sciences, Gajraula", state: "Uttar Pradesh" },
  { id: 783, name: "All India Institute of Medical Sciences, Kalyani, Nadia", state: "West Bengal" },
  { id: 784, name: "Bankura Sammilani Medical College, Bankura", state: "West Bengal" },
  { id: 785, name: "Barasat Government Medical College & Hospital", state: "West Bengal" },
  { id: 786, name: "Burdwan Medical College, Burdwan", state: "West Bengal" },
  { id: 787, name: "Calcutta National Medical College, Kolkata", state: "West Bengal" },
  { id: 788, name: "College of Medicine and JNM Hospital, Kalyani, Nadia", state: "West Bengal" },
  { id: 789, name: "College of Medicine and Sagore Dutta Hospital, Kolkata", state: "West Bengal" },
  { id: 790, name: "Coochbehar Government Medical College & Hospital, Coochbehar, WB", state: "West Bengal" },
  { id: 791, name: "Diamond Harbour Government Medical College and Hospital, West Bengal", state: "West Bengal" },
  { id: 792, name: "East West Institute of Medical Sciences and Research, Burdwan", state: "West Bengal" },
  { id: 793, name: "Employees State Insurance Corporation Medical College, Joka, Kolkata", state: "West Bengal" },
  { id: 794, name: "Gouri Devi Institute of Medical Sciences and Hospital, Durgapur", state: "West Bengal" },
  { id: 795, name: "Govt. Medical College, Kolkata", state: "West Bengal" },
  { id: 796, name: "ICARE Institute of Medical Sciences & Research, Haldia, Purba Midanpore", state: "West Bengal" },
  { id: 797, name: "Institute of Postgraduate Medical Education & Research, Kolkata", state: "West Bengal" },
  { id: 798, name: "IQ-City Medical College, Burdwan", state: "West Bengal" },
  { id: 799, name: "Jagannath Gupta Institute of Medical Sciences & Hospital, Kolkata", state: "West Bengal" },
  { id: 800, name: "Jagannath Gupta Institute of Medical Sciences and Hospital", state: "West Bengal" },
  { id: 801, name: "Jakir Hossain Medical College, Burdwan", state: "West Bengal" },
  { id: 802, name: "Jalpaiguri Government Medical College", state: "West Bengal" },
  { id: 803, name: "Jhargram Government Medical College & Hospital, Jhargram", state: "West Bengal" },
  { id: 804, name: "JIS School of Medical Science & Research, Howrah", state: "West Bengal" },
  { id: 805, name: "JMN Medical College, Nadia", state: "West Bengal" },
  { id: 806, name: "KPC Medical College, Jadavpur, Kolkata", state: "West Bengal" },
  { id: 807, name: "Krishnanagar Institute of Medical Sciences Pvt. Ltd Krishnanagar, Nadia (WB)", state: "West Bengal" },
  { id: 808, name: "Malda Medical College & Hospital, Malda", state: "West Bengal" },
  { id: 809, name: "Midnapore Medical College, Midnapore", state: "West Bengal" },
  { id: 810, name: "Murshidabad Medical College & Hospitals, Murshidabad", state: "West Bengal" },
  { id: 811, name: "Nilratan Sircar Medical College, Kolkata", state: "West Bengal" },
  { id: 812, name: "North Bengal Medical College, Darjeeling", state: "West Bengal" },
  { id: 813, name: "PKG Medical College & Hospital", state: "West Bengal" },
  { id: 814, name: "Prafulla Chandra Sen Government Medical College & Hospital", state: "West Bengal" },
  { id: 815, name: "Purulia Government Medical College & Hospital", state: "West Bengal" },
  { id: 816, name: "Raiganj Government Medical College & Hospital, Raiganj", state: "West Bengal" },
  { id: 817, name: "Rampurhat Government Medical College & Hospital, Rampurhat", state: "West Bengal" },
  { id: 818, name: "RANIGANJ INSTITUTE OF MEDICAL SCIENCE", state: "West Bengal" },
  { id: 819, name: "RG Kar Medical College, Kolkata", state: "West Bengal" },
  { id: 820, name: "Santiniketan Medical College, Bolpur, West Bengal", state: "West Bengal" },
  { id: 821, name: "Sarat Chandra Chattopadhyay Government Medical College & Hospital,", state: "West Bengal" },
  { id: 822, name: "Shri Ramkrishna Institute of Medical Sciences & Sanaka Hospitals, Durgapur", state: "West Bengal" },
  { id: 823, name: "Tamralipto Government Medical College & Hospital", state: "West Bengal" },
];
